In [1]:
import pandas as pd
import numpy as np

In [5]:
utilities = pd.read_csv("../../../Raw/utilities.csv")
substations = pd.read_csv("../../../Raw/substations.csv")
lines = pd.read_csv("../../../Raw/lines.csv")

In [6]:
# Display the first few rows of each dataset
print("Utilities")
display(utilities.head())

print("Substations")
display(substations.head())

print("Lines")
display(lines.head())

Utilities

,Utility ID,Name,Alias,Code,Type,Country,Active
0,1,Electricity Company of Ghana,ECG,ECG,Distribution,Ghana,Y
1,2,Northern Electricity Distribution Company,NEDCo,NED,Distribution,Ghana,Y
2,3,Ghana Grid Company,GRIDCo,GRD,Transmission,Ghana,Y
3,4,Volta River Authority,VRA,VRA,Generation,Ghana,Y
4,5,Compagnie Ivoirienne d'Electricite,CIE,CIE,Distribution,Cote d'Ivoire,Y

Substations

,Substation ID,Name,Short Name,Region,Country,Latitude,Longitude,Voltage (kV),Capacity (MVA),Commissioning Year,Type,Status
0,1,Achimota Substation,Achimota,Greater Accra,Ghana,5.6085,-0.2193,11,6.4,2008,Distribution,Active
1,2,Tema Substation,Tema,Greater Accra,Ghana,5.6596,-0.0226,330,48.5,1997,Transmission,Active
2,3,Mallam Substation,Mallam,Greater Accra,Ghana,5.5630,-0.2971,330,25.2,1979,Transmission,Active
3,4,Legon Substation,Legon,Greater Accra,Ghana,5.6401,-0.1799,161,241.9,2009,Transmission,Active
4,5,Kaneshie Substation,Kaneshie,Greater Accra,Ghana,5.5691,-0.2413,161,146.0,1970,Transmission,Active

Lines

,Line ID,Utility ID,Source Substation ID,Source Substation,Destination Substation ID,Destination Substation,Voltage (kV),Length (km),Capacity (MVA),Status,Line Type
0,1,2,1,Achimota Substation,2,Tema Substation,11,25.2,215.0,Active,Underground
1,2,2,1,Achimota Substation,3,Mallam Substation,11,11.0,36.4,Active,Overhead
2,3,3,1,Achimota Substation,5,Kaneshie Substation,11,5.9,277.4,Active,Overhead
3,4,1,2,Tema Substation,3,Mallam Substation,330,34.4,39.0,Active,Underground
4,5,3,2,Tema Substation,4,Legon Substation,161,19.5,186.5,Active,Underground

In [7]:
utilities.info()
print()

substations.info()
print()

lines.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Utility ID  10 non-null     int64
 1   Name        10 non-null     str
 2   Alias       10 non-null     str
 3   Code        10 non-null     str
 4   Type        10 non-null     str
 5   Country     10 non-null     str
 6   Active      10 non-null     str
dtypes: int64(1), str(6)
memory usage: 1.2 KB

<class 'pandas.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Substation ID       44 non-null     int64
 1   Name                44 non-null     str
 2   Short Name          44 non-null     str
 3   Region              44 non-null     str
 4   Country             44 non-null     str
 5   Latitude            44 non-null     float64
 6   Longitude           44 non-null     float64
 7   Voltage (kV)        44 non-null     int64
 8   Capacity (MVA)      44 non-null     float64
 9   Commissioning Year  44 non-null     int64
 10  Type                44 non-null     str
 11  Status              44 non-null     str
dtypes: float64(3), int64(3), str(6)
memory usage: 6.9 KB

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Line ID                    55 non-null     int64
 1   Utility ID                 55 non-null     int64
 2   Source Substation ID       55 non-null     int64
 3   Source Substation          55 non-null     str
 4   Destination Substation ID  55 non-null     int64
 5   Destination Substation     55 non-null     str
 6   Voltage (kV)               55 non-null     int64
 7   Length (km)                55 non-null     float64
 8   Capacity (MVA)             55 non-null     float64
 9   Status                     55 non-null     str
 10  Line Type                  55 non-null     str
dtypes: float64(2), int64(5), str(4)
memory usage: 7.7 KB

In [8]:
utilities.isnull().sum()

Utility ID    0
Name          0
Alias         0
Code          0
Type          0
Country       0
Active        0
dtype: int64

In [9]:
substations.isnull().sum()

Substation ID         0
Name                  0
Short Name            0
Region                0
Country               0
Latitude              0
Longitude             0
Voltage (kV)          0
Capacity (MVA)        0
Commissioning Year    0
Type                  0
Status                0
dtype: int64

In [10]:
lines.isnull().sum()

Line ID                      0
Utility ID                   0
Source Substation ID         0
Source Substation            0
Destination Substation ID    0
Destination Substation       0
Voltage (kV)                 0
Length (km)                  0
Capacity (MVA)               0
Status                       0
Line Type                    0
dtype: int64

In [11]:
print("Utilities duplicates:", utilities.duplicated().sum())
print("Substations duplicates:", substations.duplicated().sum())
print("Lines duplicates:", lines.duplicated().sum())

Utilities duplicates: 0
Substations duplicates: 0
Lines duplicates: 0

In [12]:
# Remove duplicates (if any)
utilities = utilities.drop_duplicates()
substations = substations.drop_duplicates()
lines = lines.drop_duplicates()

In [14]:
utilities.to_csv("../../utilities_cleaned.csv", index=False)
substations.to_csv("../../substations_cleaned.csv", index=False)
lines.to_csv("../../lines_cleaned.csv", index=False)

print("Cleaned datasets saved successfully!")

Cleaned datasets saved successfully!

In [15]:
# Verify Source and Destination Substation IDs exist

valid_ids = set(substations["Substation ID"])

invalid_source = lines[~lines["Source Substation ID"].isin(valid_ids)]
invalid_destination = lines[~lines["Destination Substation ID"].isin(valid_ids)]

print("Invalid Source IDs:", len(invalid_source))
print("Invalid Destination IDs:", len(invalid_destination))

Invalid Source IDs: 0
Invalid Destination IDs: 0

In [16]:
# Validate coordinates

invalid_coordinates = substations[
    (substations["Latitude"] < -5) |
    (substations["Latitude"] > 20) |
    (substations["Longitude"] < -20) |
    (substations["Longitude"] > 10)
]

print("Invalid coordinate records:", len(invalid_coordinates))

Invalid coordinate records: 0

In [17]:
# Check data types

print("Utilities")
print(utilities.dtypes)

print("\nSubstations")
print(substations.dtypes)

print("\nLines")
print(lines.dtypes)

Utilities
Utility ID    int64
Name            str
Alias           str
Code            str
Type            str
Country         str
Active          str
dtype: object

Substations
Substation ID           int64
Name                      str
Short Name                str
Region                    str
Country                   str
Latitude              float64
Longitude             float64
Voltage (kV)            int64
Capacity (MVA)        float64
Commissioning Year      int64
Type                      str
Status                    str
dtype: object

Lines
Line ID                        int64
Utility ID                     int64
Source Substation ID           int64
Source Substation                str
Destination Substation ID      int64
Destination Substation           str
Voltage (kV)                   int64
Length (km)                  float64
Capacity (MVA)               float64
Status                           str
Line Type                        str
dtype: object

In [18]:
print("Utilities Summary")
display(utilities.describe(include="all"))

print("Substations Summary")
display(substations.describe(include="all"))

print("Lines Summary")
display(lines.describe(include="all"))

Utilities Summary

,Utility ID,Name,Alias,Code,Type,Country,Active
count,10.00000,10,10,10,10,10,10
unique,NaN,10,10,10,3,6,2
top,NaN,Electricity Company of Ghana,ECG,ECG,Distribution,Ghana,Y
freq,NaN,1,1,1,6,5,8
mean,5.50000,NaN,NaN,NaN,NaN,NaN,NaN
std,3.02765,NaN,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN,NaN
25%,3.25000,NaN,NaN,NaN,NaN,NaN,NaN
50%,5.50000,NaN,NaN,NaN,NaN,NaN,NaN
75%,7.75000,NaN,NaN,NaN,NaN,NaN,NaN
max,10.00000,NaN,NaN,NaN,NaN,NaN,NaN

Substations Summary

,Substation ID,Name,Short Name,Region,Country,Latitude,Longitude,Voltage (kV),Capacity (MVA),Commissioning Year,Type,Status
count,44.000000,44,44,44,44,44.000000,44.000000,44.000000,44.000000,44.000000,44,44
unique,NaN,44,44,18,6,NaN,NaN,NaN,NaN,NaN,3,2
top,NaN,Achimota Substation,Achimota,Greater Accra,Ghana,NaN,NaN,NaN,NaN,NaN,Transmission,Active
freq,NaN,1,1,6,36,NaN,NaN,NaN,NaN,NaN,21,43
mean,22.500000,NaN,NaN,NaN,NaN,6.898402,-1.194868,134.545455,157.865909,1996.295455,NaN,NaN
std,12.845233,NaN,NaN,NaN,NaN,1.879404,2.314917,120.399810,139.923148,16.112366,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,4.874700,-13.580000,11.000000,6.400000,1967.000000,NaN,NaN
25%,11.750000,NaN,NaN,NaN,NaN,5.586350,-1.760000,33.000000,43.825000,1982.250000,NaN,NaN
50%,22.500000,NaN,NaN,NaN,NaN,6.184400,-0.800700,69.000000,108.550000,1999.500000,NaN,NaN
75%,33.250000,NaN,NaN,NaN,NaN,7.364200,-0.170900,161.000000,254.350000,2009.250000,NaN,NaN
max,44.000000,NaN,NaN,NaN,NaN,11.200000,2.430000,330.000000,487.600000,2022.000000,NaN,NaN

Lines Summary

,Line ID,Utility ID,Source Substation ID,Source Substation,Destination Substation ID,Destination Substation,Voltage (kV),Length (km),Capacity (MVA),Status,Line Type
count,55.00000,55.000000,55.000000,55,55.000000,55,55.000000,55.000000,55.000000,55,55
unique,NaN,NaN,NaN,28,NaN,37,NaN,NaN,NaN,2,2
top,NaN,NaN,NaN,Achimota Substation,NaN,Konongo Substation,NaN,NaN,NaN,Active,Overhead
freq,NaN,NaN,NaN,4,NaN,4,NaN,NaN,NaN,53,40
mean,28.00000,2.836364,17.872727,NaN,18.745455,NaN,141.381818,99.312727,222.400000,NaN,NaN
std,16.02082,1.718781,12.060119,NaN,11.719275,NaN,135.169097,90.275104,109.181765,NaN,NaN
min,1.00000,1.000000,1.000000,NaN,2.000000,NaN,11.000000,3.800000,32.900000,NaN,NaN
25%,14.50000,2.000000,7.500000,NaN,9.500000,NaN,22.000000,42.900000,134.550000,NaN,NaN
50%,28.00000,3.000000,16.000000,NaN,18.000000,NaN,69.000000,75.900000,229.900000,NaN,NaN
75%,41.50000,3.000000,27.000000,NaN,27.000000,NaN,330.000000,129.600000,292.100000,NaN,NaN
max,55.00000,9.000000,40.000000,NaN,43.000000,NaN,330.000000,426.000000,506.300000,NaN,NaN